name: Sync Github Open Data repository and its metadata to OpenCoDE.de

on:
  workflow_dispatch:

jobs:
  name: Sync Github Open Data repository and its metadata to OpenCoDE.de
  runs-on: ubuntu-latest
  steps:
    - name: Sync Github Open Data repository
      uses: robert-koch-institut/OpenData-Workflows/Sync_OpenData_repo_to_OpenCoDE@main
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OPENCODE_TOKEN: ${{ secrets.OPENCODE_TOKEN }}
        GROUP_ID: ${{inputs.OPENCODE_GROUPID}}
        ACCESS_USER: ${{inputs.OPENCODE_ACCESS_USER}}
        #          # REPO_PATH: The repository name must not start or end with a special character and must not contain consecutive special characters
        ZENODOJSON_PATH: ${{inputs.OPENCODE_ZENODOJSON_PATH}}