name: Zenodo Dataset Draft with DOI Reservation

on:
  workflow_dispatch:

env:
    RECORD_ID: ''
    github_token: ${{ secrets.WORKFLOW_TOKEN }}

jobs:
  manage-zenodo-record:
    runs-on: ubuntu-latest
    outputs:
      RECORD_ID: ${{ steps.manage_record.outputs.RECORD_ID }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Manage Zenodo Record
      id: manage_record

      run: |
        if [[ -z "$RECORD_ID" ]]; then
          # Keine vorhandene Record ID, erstelle neuen Datensatz und speichert die Record ID
            response=$(curl -H "Content-Type: application/json" \
                           -H "Authorization: Bearer ${{ secrets.ZENODO_TOKEN }}" \
                           -X POST \
                           -d @Metadaten/zenodo.json \
                           "https://zenodo.org/api/records")
            echo "$response"
            echo "RECORD_ID="$(echo $response | jq -r '.id')"" >> $GITHUB_ENV 
        fi

    - name: Save Record ID
      run: sed -i "s/RECORD_ID:\ ''/RECORD_ID:\ '${{ env.RECORD_ID }}'/" ./.github/workflows/Zenodo.yml

    - name: Add and Commit Changes 
      uses: EndBug/add-and-commit@v9
      with:
        message: 'Update Metadata'
        author_name: 'RKIOpenData'
