name: Zenodo Dataset Draft with DOI Reservation

on:
  workflow_dispatch:

jobs:
  manage-zenodo-record:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Manage Zenodo Record
      id: manage_record

      run: |
        EXISTING_RECORD_ID=$(jq -r '.ID' Metadaten/new_zenodo.json)
        echo $EXISTING_RECORD_ID
        echo $(jq '.metadata' Metadaten/new_zenodo.json) 
        if [ "$EXISTING_RECORD_ID" == "null" ] ; then
          # Keine vorhandene Record ID, erstelle neuen Datensatz und speichert die Record ID
            response=$(curl -H "Content-Type: application/json" \
                           -H "Authorization: Bearer ${{ secrets.ZENODO_TOKEN }}" \
                           -X POST \
                           -d @Metadaten/new_zenodo.json \
                           "https://zenodo.org/api/records")
          # Speichere die Response in zenodo.json und überschreibe den alten Inhalt
          echo "$response" > Metadaten/new_zenodo.json
        fi

    - name: Add and Commit Changes 
      uses: EndBug/add-and-commit@v9
      with:
        message: 'Update Metadata'
        author_name: 'RKIOpenData'
